

sudo: false

install:
  - npm install -g elm@0.19.1-3
  - npm install -g elm-test@0.19.1
  - npm install -g webpack
  - npm install tone
  - npm install


script:
  - bash build.sh build
  - elm-test


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: ./dist
  on:
    branch: master